version: '3'

services:
  laravel:
    image: luanpartes/laravel-app:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: luanpartes/nginx:laravel
    container_name: nginx
    networks:
      - laranet
    
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge